services:
  - type: web
    name: shieldscan
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: GOOGLE_SAFE_BROWSING_KEY
        sync: false
    disk:
      name: shieldscan-db
      mountPath: /data
      sizeGB: 1
